import { createHash } from "node:crypto";

export const DEFAULT_PUBLIC_BASE_URL = "https://pair-lab-imperial.github.io/nfc-inventory/";

export function sha256Hex(value) {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

function stableId(namespace, value) {
  const bytes = createHash("sha256").update(`${namespace}\0${value}`).digest().subarray(0, 16);
  bytes[6] = (bytes[6] & 0x0f) | 0x50;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = bytes.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function sqlValue(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replaceAll("'", "''")}'`;
}

function csvValue(value) {
  const text = String(value ?? "");
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

export function buildDummyNfcLabels(equipment, publicBaseUrl = DEFAULT_PUBLIC_BASE_URL) {
  const baseUrl = new URL(publicBaseUrl);
  return equipment.map((item) => {
    const token = `demo-${item.assetCode.toLocaleLowerCase("en-GB")}-v1`;
    const url = new URL(baseUrl);
    url.searchParams.set("t", token);
    return {
      id: stableId("dummy-nfc-label", item.assetCode),
      auditId: stableId("dummy-nfc-label-audit", item.assetCode),
      assetCode: item.assetCode,
      equipmentName: item.name,
      token,
      tokenHash: sha256Hex(token),
      tokenHint: token.slice(-8),
      url: url.toString(),
    };
  });
}

export function buildNfcLabel({ assetCode, equipmentName = "", token, publicBaseUrl = DEFAULT_PUBLIC_BASE_URL }) {
  const normalizedAssetCode = String(assetCode || "").trim().toUpperCase();
  if (!/^[A-Z][A-Z0-9]{1,7}-\d{3,6}$/.test(normalizedAssetCode)) {
    throw new Error("assetCode must look like ROB-003");
  }
  if (!/^[A-Za-z0-9_-]{8,128}$/.test(token || "")) {
    throw new Error("token must contain 8–128 URL-safe letters, numbers, underscores or hyphens");
  }
  const tokenHash = sha256Hex(token);
  const url = new URL(publicBaseUrl);
  url.searchParams.set("t", token);
  return {
    id: stableId("nfc-label", `${normalizedAssetCode}/${tokenHash}`),
    auditId: stableId("nfc-label-audit", `${normalizedAssetCode}/${tokenHash}`),
    assetCode: normalizedAssetCode,
    equipmentName,
    token,
    tokenHash,
    tokenHint: token.slice(-8),
    url: url.toString(),
  };
}

export function generateDummyNfcSql(labels) {
  const lines = [
    "-- Generated by scripts/build-dummy-nfc-labels.mjs. Do not edit by hand.",
    "-- Temporary demo tokens: replace before locking physical NFC tags.",
    "-- Existing active label associations are never overwritten.",
    "PRAGMA foreign_keys = ON;",
    "",
  ];
  for (const label of labels) {
    lines.push(
      `INSERT INTO nfc_labels (id, equipment_id, token_hash, token_hint, scan_url, status, notes) SELECT ${sqlValue(label.id)}, equipment.id, ${sqlValue(label.tokenHash)}, ${sqlValue(label.tokenHint)}, ${sqlValue(label.url)}, 'active', 'Temporary dummy NFC association' FROM equipment WHERE equipment.asset_code = ${sqlValue(label.assetCode)} COLLATE NOCASE AND NOT EXISTS (SELECT 1 FROM nfc_labels current_label WHERE current_label.equipment_id = equipment.id AND current_label.status = 'active') ON CONFLICT(id) DO UPDATE SET scan_url = COALESCE(nfc_labels.scan_url, excluded.scan_url);`,
    );
    const auditJson = JSON.stringify({
      assetCode: label.assetCode,
      tokenHint: label.tokenHint,
      status: "active",
      source: "dummy-seed",
    });
    lines.push(
      `INSERT INTO audit_events (id, actor_type, actor_name, action, entity_type, entity_id, after_json) SELECT ${sqlValue(label.auditId)}, 'system', 'dummy-nfc-seed', 'nfc_label.created', 'nfc_label', label.id, ${sqlValue(auditJson)} FROM nfc_labels label WHERE label.id = ${sqlValue(label.id)} ON CONFLICT(id) DO NOTHING;`,
    );
  }
  return `${lines.join("\n")}\n`;
}

export function generateDummyNfcManifest(labels) {
  const rows = [
    ["asset_code", "equipment_name", "dummy_token", "nfc_url", "token_hint"],
    ...labels.map((label) => [label.assetCode, label.equipmentName, label.token, label.url, label.tokenHint]),
  ];
  return `${rows.map((row) => row.map(csvValue).join(",")).join("\n")}\n`;
}

export function generateReplacementNfcSql(label, previousStatus = "replaced") {
  if (!new Set(["lost", "replaced", "retired"]).has(previousStatus)) {
    throw new Error("previousStatus must be lost, replaced or retired");
  }
  const auditJson = JSON.stringify({
    assetCode: label.assetCode,
    tokenHint: label.tokenHint,
    status: "active",
    previousStatus,
  });
  return [
    "-- Generated NFC label replacement. Apply this file once.",
    "PRAGMA foreign_keys = ON;",
    `UPDATE nfc_labels SET status = ${sqlValue(previousStatus)}, retired_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE equipment_id = (SELECT id FROM equipment WHERE asset_code = ${sqlValue(label.assetCode)} COLLATE NOCASE) AND status = 'active' AND id <> ${sqlValue(label.id)};`,
    `INSERT INTO nfc_labels (id, equipment_id, token_hash, token_hint, scan_url, status, notes) SELECT ${sqlValue(label.id)}, equipment.id, ${sqlValue(label.tokenHash)}, ${sqlValue(label.tokenHint)}, ${sqlValue(label.url)}, 'active', 'Generated replacement NFC association' FROM equipment WHERE equipment.asset_code = ${sqlValue(label.assetCode)} COLLATE NOCASE ON CONFLICT(id) DO UPDATE SET scan_url = excluded.scan_url, status = 'active', retired_at = NULL, notes = excluded.notes;`,
    `INSERT INTO audit_events (id, actor_type, actor_name, action, entity_type, entity_id, after_json) SELECT ${sqlValue(label.auditId)}, 'admin', 'nfc-label-script', 'nfc_label.replaced', 'nfc_label', label.id, ${sqlValue(auditJson)} FROM nfc_labels label WHERE label.id = ${sqlValue(label.id)} ON CONFLICT(id) DO NOTHING;`,
    "",
  ].join("\n");
}
